### ISSUE TITLE
Per Terminal

### ISSUE THREAD

**Issue by axgkl** [weizerwolf/frei3VideoDownloader#1]
Hey, danke fuer das Ding.

Ohne in den Source Code geschaut zu haben - hast du evtl. eine cmdline version unter Linux zum Runterladen parat?

**Comment by weizerwolf** [comment]
> Hey, danke fuer das Ding.
> 
> Ohne in den Source Code geschaut zu haben - hast du evtl. eine cmdline version unter Linux zum Runterladen parat?

**Comment by weizerwolf** [comment]
> Hey, danke fuer das Ding.
> 
> Ohne in den Source Code geschaut zu haben - hast du evtl. eine cmdline version unter Linux zum Runterladen parat?

entschuldige bitte für die späte Antwort, ich hab die Email übersehen und erst beim Aufräumen meines Postfaches gefunden.
Theoretisch könnte ich noch eine Kommandozeilenversion einbauen, aber das werde ich vorerst zeitlich nicht schaffen.
Außerdem ist mir die Weiterentwicklung und Wartung von frei3 gerade wichtiger. ;)
Aber du kannst ganz einfach mit ffmpeg über die Kommandozeile herunterladen, anders macht es mein Programm auch nicht.
Du brauchst im Prinzip die URL für die MPD Datei, die du mit der UUID des Beitrags selbst erstellen kannst.

Beispiel, wenn die Beitrags URL folgende ist: https://www.frei3.de/article/0cf02b89-5e44-46c1-8622-8c2854d884dc
Dann ist die URL zur MPD Datei diese hier: https://media.frei3.de/files/video/0cf02b89-5e44-46c1-8622-8c2854d884dc/dash/video.mpd
vorausgesetzt, der Beitrag enthält ein direkt auf frei3 hochgeladenes Video.

Vor dem Download musst du noch ffmpeg installieren, z.B. unter Ubuntu/Debian mit:
`sudo apt-get install ffmpeg`

Jetzt kannst du folgendes mit ffprobe tun um die vorhandenen Streams in der Konsole anzuzeigen:
`ffprobe -v quiet -print_format json -show_format -show_streams https://media.frei3.de/files/video/0cf02b89-5e44-46c1-8622-8c2854d884dc/dash/video.mpd`

Für die Konvertierung nimmst du dann den jeweiligen Index des Video- und Audio-Streams, den du herunterladen willst für ffmpeg.
in diesem Fall nehme ich mal als Beispiel den zweiten für 720p und den dritten für Audio:
`ffmpeg -i https://media.frei3.de/files/video/0cf02b89-5e44-46c1-8622-8c2854d884dc/dash/video.mpd -map 0:2 -map 0:3 -codec copy /pfad/zu/deinem/video.mp4`

Da es momentan nur einen Audio-Stream gibt kannst du dir eigentlich den ersten Schritt mit ffprobe sparen, denn es geht eigentlich nur das hier:
`-map 0:0 -map 0:3` für 240p
`-map 0:1 -map 0:3` für 480p
`-map 0:2 -map 0:3` für 720p

Du kannst auch das Video direkt abspielen mit:
`ffplay https://media.frei3.de/files/video/0cf02b89-5e44-46c1-8622-8c2854d884dc/dash/video.mpd`

Wie gesagt, wenn ich zeitlich etwas mehr Luft habe, dann implementiere ich das vielleicht noch als Kommandozeilenprogramm.
Mal sehen, bis dahin hoffe ich das du mit meiner Anleitung erfolg hast. :)

**Comment by axgkl** [comment]
oh sorry - total uebersehen, muss mal paar noise subscriptions loeschen hier.

Hat super geklappt, danke!
